trigger:
- master
- develop

variables:
  sdk_version: 3.0.x
  dockerRepositoryRoot: sannel
  dockerRepositoryName: house.gateway
  dockerTagBase: $(Build.SourceBranchName)-$(Build.BuildId)
  imageName: $(dockerRepositoryRoot)/$(dockerRepositoryName):$(dockerTagBase)
  projectFolder: Sannel.House.Gateway
  mainProjectPath: src/$(projectFolder)/$(projectFolder).csproj
  mainConfigPath: src/$(projectFolder)/app_config
  tagVersion: 3.0
  tagCodeName: buster
  hasTests: false
  disableLinux: false
  disableArm64: false
  disableWindows: false
  disableOSX: true

name: $(date:yyyy.MM.dd)$(rev:.rr)

jobs:
- job: 'osx'
  pool:
    vmImage: macOS-10.13
  condition: ne(variables['disableOSX'], 'true')
  steps:
  - task: UseDotNet@2
    displayName: 'Use .NET Core sdk $(sdk_version)'
    inputs:
      packageType: 'sdk'
      version: '$(sdk_version)'
      includePreviewVersions: false
  - task: DotNetCoreCLI@2
    displayName: 'dotnet restore'
    inputs:
      command: custom
      projects: src/**/*.csproj
      custom: restore
      arguments: '-r osx-x64 --configfile .nuget/nuget.config'
      feedsToUse: config
      nugetConfigPath: .nuget/nuget.config
      externalFeedCredentials: 'Sannel House MyGet'
  - task: DotNetCoreCLI@2
    displayName: 'dotnet build Release'
    inputs:
      projects: $(mainProjectPath)
      arguments: '-r osx-x64 -c Release'
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  - task: DotNetCoreCLI@2
    displayName: 'dotnet build Debug'
    inputs:
      projects: $(mainProjectPath)
      arguments: '-r osx-x64 -c Debug'
    condition: and(succeeded(), ne(variables['Build.SourceBranch'], 'refs/heads/master'))
  - task: DotNetCoreCLI@2
    displayName: 'dotnet publish'
    inputs:
      command: publish
      publishWebProjects: false
      projects: $(mainProjectPath)
      arguments: '-r osx-x64 -o $(Build.StagingDirectory)'
      zipAfterPublish: false
  - task: DotNetCoreCLI@2
    displayName: 'dotnet restore'
    inputs:
      command: custom
      projects: '**/*Tests.csproj'
      custom: restore
      arguments: '-r osx-x64 --configfile .nuget/nuget.config'
      feedsToUse: config
      nugetConfigPath: .nuget/nuget.config
      externalFeedCredentials: 'Sannel House MyGet'
    condition: eq(variables['hasTests'], 'true')
  - task: DotNetCoreCLI@2
    displayName: 'dotnet test'
    inputs:
      projects: '**/*Tests.csproj'
      command: test
      arguments: '--collect "Code coverage"'
      publishTestResults: true
    condition: eq(variables['hasTests'], 'true')
  - task: CopyFiles@2
    displayName: 'Copy Files to: $(Build.StagingDirectory)/$(projectFolder)/app_config/'
    inputs:
      SourceFolder: '$(mainConfigPath)'
      Contents: |
        **/*.json
        **/*.yml
        **/*.pfx
        **/*.crt
      TargetFolder: '$(Build.StagingDirectory)/$(projectFolder)/app_config/'
  - powershell: |
      New-Item -Type Directory -Force $(Build.StagingDirectory)/$(projectFolder)/app_data/
      New-Item -Type File -Force $(Build.StagingDirectory)/$(projectFolder)/app_data/.hold
    displayName: 'Prepare Items'
  - task: PublishPipelineArtifact@0
    displayName: 'Publish Pipeline Artifact'
    inputs:
      artifactName: 'osx-x64'
      targetPath: '$(Build.StagingDirectory)'


- job: linux_arm
  pool:
    vmImage: ubuntu-latest
  condition: ne(variables['disableLinux'], 'true')
  steps:
    - task: UseDotNet@2
      displayName: 'Use .NET Core sdk $(sdk_version)'
      inputs:
        packageType: 'sdk'
        version: '$(sdk_version)'
        includePreviewVersions: false
    - powershell: |
        # Write your commands here
        sudo apt-get update
        sudo apt-get install -y qemu qemu-user-static qemu-user binfmt-support
        Copy-Item -Verbose /usr/bin/qemu-arm-static $(Build.StagingDirectory)
        # Use the environment variables input below to pass secret variables to this script
      displayName: 'Install qemu'
    - task: DotNetCoreCLI@2
      displayName: 'dotnet restore'
      inputs:
        command: custom
        projects: $(mainProjectPath)
        custom: restore
        arguments: '-r linux-arm --configfile .nuget/nuget.config'
        feedsToUse: config
        nugetConfigPath: .nuget/nuget.config
        externalFeedCredentials: 'Sannel House MyGet'
    - task: DotNetCoreCLI@2
      displayName: 'dotnet build Release'
      inputs:
        projects: $(mainProjectPath)
        arguments: '-r linux-arm -c Release'
      condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
    - task: DotNetCoreCLI@2
      displayName: 'dotnet build Debug'
      inputs:
        projects: $(mainProjectPath)
        arguments: '-r linux-arm -c Debug'
      condition: and(succeeded(), ne(variables['Build.SourceBranch'], 'refs/heads/master'))
    - task: DotNetCoreCLI@2
      displayName: 'dotnet publish'
      inputs:
        command: publish
        publishWebProjects: false
        projects: $(mainProjectPath)
        arguments: '-r linux-arm -o $(Build.StagingDirectory)'
        zipAfterPublish: false
    - task: CopyFiles@2
      displayName: 'Copy Files to: $(Build.StagingDirectory)/$(projectFolder)/app_config/'
      inputs:
        SourceFolder: '$(mainConfigPath)'
        Contents: |
          **/*.json
          **/*.yml
          **/*.pfx
          **/*.crt
        TargetFolder: '$(Build.StagingDirectory)/$(projectFolder)/app_config/'
    - powershell: |
        New-Item -Type Directory -Force $(Build.StagingDirectory)/$(projectFolder)/app_data/
        New-Item -Type File -Force $(Build.StagingDirectory)/$(projectFolder)/app_data/.hold
        
        copy-item -Force -Verbose build/linux-arm/Dockerfile $(Build.StagingDirectory)/
      displayName: 'Prepare Items'
    - task: Docker@1
      displayName: 'Run an image '
      inputs:
        containerregistrytype: 'Container Registry'
        dockerRegistryEndpoint: 'Docker Hub'
        command: 'Run an image'
        arguments: '--rm --privileged'
        imageName: ' multiarch/qemu-user-static:register'
        containerCommand: '--reset'
    - task: Docker@0
      displayName: 'Build an image arm'
      inputs:
        containerregistrytype: 'Container Registry'
        dockerRegistryConnection: 'Docker Hub'
        dockerFile: '$(Build.StagingDirectory)/Dockerfile'
        buildArguments: 'tag=$(tagVersion)-$(tagCodeName)-slim-arm32v7'
        defaultContext: false
        context: '$(Build.StagingDirectory)'
        imageName: '$(imageName)-linux-arm32v7'
    - powershell: |
        $img = "$(imageName)".ToLower()
        docker save -o $(Build.StagingDirectory)/$(dockerRepositoryRoot).$(dockerRepositoryName).linux.arm32v7.tar "${img}-linux-arm32v7"
        bzip2 -9 $(Build.StagingDirectory)/$(dockerRepositoryRoot).$(dockerRepositoryName).linux.arm32v7.tar
      displayName: 'export image'
    - powershell: |
        # Write your powershell commands here.
        
        Remove-Item -Force $(Build.StagingDirectory)/Dockerfile*
        Remove-Item -Force $(Build.StagingDirectory)/qemu*
        
        # Use the environment variables input below to pass secret variables to this script.
      displayName: 'clean up copy'
    - task: PublishPipelineArtifact@0
      displayName: 'Publish Pipeline Artifact'
      inputs:
        artifactName: 'linux-arm'
        targetPath: '$(Build.StagingDirectory)'

- job: linux_arm64
  pool:
    vmImage: ubuntu-latest
  condition: and(ne(variables['disableLinux'], 'true'), ne(variables['disableArm64'], 'true'))
  steps:
    - task: UseDotNet@2
      displayName: 'Use .NET Core sdk $(sdk_version)'
      inputs:
        packageType: 'sdk'
        version: '$(sdk_version)'
        includePreviewVersions: false
    - powershell: |
        # Write your commands here
        sudo apt-get update
        sudo apt-get install -y qemu qemu-user-static qemu-user binfmt-support
        Copy-Item -Verbose /usr/bin/qemu-aarch64-static $(Build.StagingDirectory)
        # Use the environment variables input below to pass secret variables to this script
      displayName: 'Install qemu'
    - task: DotNetCoreCLI@2
      displayName: 'dotnet restore'
      inputs:
        command: custom
        projects: $(mainProjectPath)
        custom: restore
        arguments: '-r linux-arm64 --configfile .nuget/nuget.config'
        feedsToUse: config
        nugetConfigPath: .nuget/nuget.config
        externalFeedCredentials: 'Sannel House MyGet'
    - task: DotNetCoreCLI@2
      displayName: 'dotnet build Release'
      inputs:
        projects: $(mainProjectPath)
        arguments: '-r linux-arm64 -c Release'
      condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
    - task: DotNetCoreCLI@2
      displayName: 'dotnet build Debug'
      inputs:
        projects: $(mainProjectPath)
        arguments: '-r linux-arm64 -c Debug'
      condition: and(succeeded(), ne(variables['Build.SourceBranch'], 'refs/heads/master'))
    - task: DotNetCoreCLI@2
      displayName: 'dotnet publish'
      inputs:
        command: publish
        publishWebProjects: false
        projects: $(mainProjectPath)
        arguments: '-r linux-arm64 -o $(Build.StagingDirectory)'
        zipAfterPublish: false
    - task: CopyFiles@2
      displayName: 'Copy Files to: $(Build.StagingDirectory)/$(projectFolder)/app_config/'
      inputs:
        SourceFolder: '$(mainConfigPath)'
        Contents: |
          **/*.json
          **/*.yml
          **/*.pfx
          **/*.crt
        TargetFolder: '$(Build.StagingDirectory)/$(projectFolder)/app_config/'
    - powershell: |
        New-Item -Type Directory -Force $(Build.StagingDirectory)/$(projectFolder)/app_data/
        New-Item -Type File -Force $(Build.StagingDirectory)/$(projectFolder)/app_data/.hold
        
        copy-item -Force -Verbose build/linux-arm64/Dockerfile $(Build.StagingDirectory)/
      displayName: 'Prepare Items'
    - task: Docker@1
      displayName: 'Run an image '
      inputs:
        containerregistrytype: 'Container Registry'
        dockerRegistryEndpoint: 'Docker Hub'
        command: 'Run an image'
        arguments: '--rm --privileged'
        imageName: ' multiarch/qemu-user-static:register'
        containerCommand: '--reset'
    - task: Docker@0
      displayName: 'Build an image arm'
      inputs:
        containerregistrytype: 'Container Registry'
        dockerRegistryConnection: 'Docker Hub'
        dockerFile: '$(Build.StagingDirectory)/Dockerfile'
        buildArguments: 'tag=$(tagVersion)-$(tagCodeName)-slim-arm64v8'
        defaultContext: false
        context: '$(Build.StagingDirectory)'
        imageName: '$(imageName)-linux-arm64v8'
    - powershell: |
        $img = "$(imageName)".ToLower()
        docker save -o $(Build.StagingDirectory)/$(dockerRepositoryRoot).$(dockerRepositoryName).linux.arm64v8.tar "${img}-linux-arm64v8"
        bzip2 -9 $(Build.StagingDirectory)/$(dockerRepositoryRoot).$(dockerRepositoryName).linux.arm64v8.tar
      displayName: 'export image'
    - powershell: |
        # Write your powershell commands here.
        
        Remove-Item -Force $(Build.StagingDirectory)/Dockerfile*
        Remove-Item -Force $(Build.StagingDirectory)/qemu*
        
        # Use the environment variables input below to pass secret variables to this script.
      displayName: 'clean up copy'
    - task: PublishPipelineArtifact@0
      displayName: 'Publish Pipeline Artifact'
      inputs:
        artifactName: 'linux-arm64'
        targetPath: '$(Build.StagingDirectory)'

- job: linux_x64
  pool:
    vmImage: ubuntu-latest
  condition: ne(variables['disableLinux'], 'true')
  steps:
    - task: UseDotNet@2
      displayName: 'Use .NET Core sdk $(sdk_version)'
      inputs:
        packageType: 'sdk'
        version: '$(sdk_version)'
        includePreviewVersions: false
    - task: DotNetCoreCLI@2
      displayName: 'dotnet restore'
      inputs:
        command: custom
        projects: $(mainProjectPath)
        custom: restore
        arguments: '-r linux-x64 --configfile .nuget/nuget.config'
        feedsToUse: config
        nugetConfigPath: .nuget/nuget.config
        externalFeedCredentials: 'Sannel House MyGet'

    - task: DotNetCoreCLI@2
      displayName: 'dotnet build Release'
      inputs:
        projects: $(mainProjectPath)
        arguments: '-r linux-x64 -c Release'
      condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))

    - task: DotNetCoreCLI@2
      displayName: 'dotnet build Debug'
      inputs:
        projects: $(mainProjectPath)
        arguments: '-r linux-x64 -c Debug'
      condition: and(succeeded(), ne(variables['Build.SourceBranch'], 'refs/heads/master'))

    - task: DotNetCoreCLI@2
      displayName: 'dotnet publish'
      inputs:
        command: publish
        publishWebProjects: false
        projects: $(mainProjectPath)
        arguments: '-r linux-x64 -o $(Build.StagingDirectory)'
        zipAfterPublish: false

    - task: DotNetCoreCLI@2
      displayName: 'dotnet restore'
      inputs:
        command: custom
        projects: '**/*Tests.csproj'
        custom: restore
        arguments: '-r linux-x64 --configfile .nuget/nuget.config'
        feedsToUse: config
        nugetConfigPath: .nuget/nuget.config
        externalFeedCredentials: 'Sannel House MyGet'
      condition: eq(variables['hasTests'], 'true')
    - task: DotNetCoreCLI@2
      displayName: 'dotnet test'
      inputs:
        projects: '**/*Tests.csproj'
        command: test
        arguments: '--collect "Code coverage"'
        publishTestResults: true
      condition: eq(variables['hasTests'], 'true')
    - task: CopyFiles@2
      displayName: 'Copy Files to: $(Build.StagingDirectory)/$(projectFolder)/app_config/'
      inputs:
        SourceFolder: '$(mainConfigPath)'
        Contents: |
          **/*.json
          **/*.yml
          **/*.pfx
          **/*.crt
        TargetFolder: '$(Build.StagingDirectory)/$(projectFolder)/app_config/'

    - powershell: |
        New-Item -Type Directory -Force $(Build.StagingDirectory)/$(projectFolder)/app_data/
        New-Item -Type File -Force $(Build.StagingDirectory)/$(projectFolder)/app_data/.hold
        
        copy-item -Force -Verbose build/linux-x64/Dockerfile $(Build.StagingDirectory)/
      displayName: 'Prepare Items'

    - task: Docker@0
      displayName: 'Build an image x64'
      inputs:
        containerregistrytype: 'Container Registry'
        dockerRegistryConnection: 'Docker Hub'
        dockerFile: '$(Build.StagingDirectory)/Dockerfile'
        buildArguments: 'tag=$(tagVersion)'
        defaultContext: false
        context: '$(Build.StagingDirectory)'
        imageName: '$(imageName)-linux-x64'
    - powershell: |
        $img = "$(imageName)".ToLower()
        docker save -o $(Build.StagingDirectory)/$(dockerRepositoryRoot).$(dockerRepositoryName).linux.x64.tar "${img}-linux-x64"
        bzip2 -9 $(Build.StagingDirectory)/$(dockerRepositoryRoot).$(dockerRepositoryName).linux.x64.tar
      displayName: 'export image'

    - powershell: |
        # Write your powershell commands here.
        
        Remove-Item -Force $(Build.StagingDirectory)/Dockerfile*
        
        # Use the environment variables input below to pass secret variables to this script.
      displayName: 'clean up'

    - task: PublishPipelineArtifact@0
      displayName: 'Publish Pipeline Artifact'
      inputs:
        artifactName: 'linux-x64'
        targetPath: '$(Build.StagingDirectory)'

  - template: build/tasks/windows.yaml
    parameters:
      release: '1803'
      arch: 'x64'