trigger:
- master
- develop

variables:
  sdk_version: 3.1.x
  dockerRepositoryRoot: sannel
  dockerRepositoryName: house.gateway
  dockerTagBase: $(Build.SourceBranchName)-$(Build.BuildId)
  imageName: $(dockerRepositoryRoot)/$(dockerRepositoryName):$(dockerTagBase)
  projectFolder: Sannel.House.Gateway
  mainProjectPath: src/$(projectFolder)/$(projectFolder).csproj
  mainConfigPath: src/$(projectFolder)/app_config
  tagVersion: 3.1
  tagCodeName: buster
  hasTests: false
  disableLinux: false
  disableArm64: false
  disableWindows: false
  disableOSX: false

name: $(date:yyyy.MM.dd)$(rev:.rr)

jobs:
- template: build/tasks/linux-arm.yaml
  parameters:
    arch: arm32
    archLong: arm32v7
    ridSuffix: arm
    qemuStatic: qemu-arm-static

- template: build/tasks/linux-arm.yaml
  parameters:
    arch: arm64
    archLong: arm64v8

- template: build/tasks/linux.yaml