---
GlobalConfiguration:
  BaseUrl: https://house.dev.local
Authentication:
  AuthorityUrl: https://users.house.dev.local
  Schema: houseapi
  ApiName: houseapi
  DisableRequireHttpsMetadata: true
Cert:
  Install: true
  Crt: app_config/Sannel Software - Dev - CA.crt
Kestrel:
  Endpoints:
    HTTPS:
      Url: https://*:443
      Certificate:
        Path: app_config/house.dev.local.pfx
        Password: "@Password1"
