---
GlobalConfiguration:
  BaseUrl: http://house.dev.local
Authentication:
  AuthorityUrl: http://house.dev.local
  Schema: houseapi
  ApiName: houseapi
  ApiSecret: GatewayPassword
  DisableRequireHttpsMetadata: true
Cors:
  Origins:
  - Any
  Headers:
  - Any
  Methods:
  - Any
  AllowWildCardDomains: false
  AllowCredentials: false


Cert:
  Install: false
  Crt: app_config/Sannel Software - Dev - CA.crt
Kestrel:
  Endpoints:
    HTTP:
      Url: http://*:8080
#    HTTPS:
#      Url: https://*:443
#      Certificate:
#        Path: app_config/house.dev.local.pfx
#        Password: "@Password1"
